'-Wall', 
'-Wextra', 
'-Wno-long-long', 
'-Wno-variadic-macros', 
'-fexceptions', 
'-stdlib=libc++', 
'-std=c11', 
'-x', 'c', 
'-I', '/Users/zl03jsj/Documents/mupdf/.', 
'-resource-dir=/Users/zl03jsj/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../clang_includes', 
'-isystem', '/Users/zl03jsj/Documents/mupdf/include', 
'-isystem', '/Users/zl03jsj/Documents/mupdf/generated', 
'-isystem', '/Users/zl03jsj/Documents/mupdf/thirdparty/freetype/include', 
'-isystem', '/usr/include', 
'-isystem', '/usr/local/include', 
'-isystem', '/Library/Developer/CommandLineTools/usr/include', 
'-isystem', '/Library/Developer/CommandLineTools/usr/include/c++/v1', 
'-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1', 
'-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include', 
'-isystem', '/System/Library/Frameworks',
'-isystem', '/Library/Frameworks',
'-isystem', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include', 
'-isystem', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include',
'-fspell-checking']
