
/**********************************************************************
//	该文件用于定义多语言界面版本的字符串的ID
//**********************************************************************/

#ifndef HSMUISTRS_H
#define HSMUISTRS_H

#define IDCMUI_IDOK					1
#define IDCMUI_IDCANCEL				2
#define IDCMUI_IDABORT			    3
#define IDCMUI_IDRETRY			    4
#define IDCMUI_IDIGNORE			    5
#define IDCMUI_IDYES			    6
#define IDCMUI_IDNO					7
#define IDCMUI_IDCLOSE				8
#define IDCMUI_IDHELP				9
#define IDCMUI_IDTRYAGAIN			10
#define IDCMUI_IDCONTINUE			11
#define IDCMUI_IDOPEN				12

//控件名称定义

//SPECIAL USERS
#define IDSMUI_HANDSIGNCTL_NAME_SP_WPS		21
#define IDSMUI_HANDSIGNCTL_NAME_SP_OFFICE	22

//SERVER
#define IDSMUI_HANDSIGNCTL_NAME_SVR_WPS		23
#define IDSMUI_HANDSIGNCTL_NAME_SVR_OFFICE	24

//单机版本
#define IDSMUI_HANDSIGNCTL_NAME_WPS		25
#define IDSMUI_HANDSIGNCTL_NAME_OFFICE	26

#if defined(SPECIALUSER)
	#if defined(NTKO_SUPPORT_WPS)
		#define IDSMUI_HANDSIGNCTL_NAME (IDSMUI_HANDSIGNCTL_NAME_SP_WPS)
	#else
		#define IDSMUI_HANDSIGNCTL_NAME (IDSMUI_HANDSIGNCTL_NAME_SP_OFFICE)
	#endif
#else
	#if defined(NTKO_SUPPORT_SERVERSIGN)
		#if defined(NTKO_SUPPORT_WPS)
			#define IDSMUI_HANDSIGNCTL_NAME (IDSMUI_HANDSIGNCTL_NAME_SVR_WPS)
		#else
			#define IDSMUI_HANDSIGNCTL_NAME (IDSMUI_HANDSIGNCTL_NAME_SVR_OFFICE)
		#endif			
	#else
		#if defined(NTKO_SUPPORT_WPS)
			#define IDSMUI_HANDSIGNCTL_NAME (IDSMUI_HANDSIGNCTL_NAME_WPS)
		#else
			#define IDSMUI_HANDSIGNCTL_NAME (IDSMUI_HANDSIGNCTL_NAME_OFFICE)
		#endif	
	#endif
#endif

#if defined(NTKO_CUSTOM_JIANGSU_CA)
	#define IDSMUI_LVSELSIGNSFIRSTCOLUMN0   1000
	#define IDSMUI_LVSELSIGNSFIRSTCOLUMN1	1001
	#define IDSMUI_LVSELSIGNSFIRSTCOLUMN2 	1002
#else
	#define IDSMUI_LVSELSIGNSFIRSTCOLUMN0   30
	#define IDSMUI_LVSELSIGNSFIRSTCOLUMN1	31
	#define IDSMUI_LVSELSIGNSFIRSTCOLUMN2 	32
#endif
#define IDSMUI_DOCSIGNSFIRSTCOLUMN1 	33
#define IDSMUI_DOCSIGNSFIRSTCOLUMN2 	34
#define IDSMUI_NOSECSIGNCONTROL    		35
#define IDSMUI_MSGBOXTITLE_TIP     		36
#define IDSMUI_ABOUTDLGTITLE       		37
#define IDSMUI_ABOUTDLG_SVRTITLE   		38
#define IDSMUI_CFGDLG_TITLE        		39
#define IDSMUI_CFGDLG_SVRTITLE     		40
#define IDSMUI_CFGDLG_SYSCONF      		41
#define IDSMUI_SVRFAIL_INVALIDVER  		42
#define IDSMUI_SVRFAIL_WITHCODE    		43
#define IDSMUI_SVRFAIL_PARSEERROR  		44
#define IDSMUI_SVRFAIL_CONNECT     		45

#if defined(NTKO_CUSTOM_HENAN_XINGONGDA)
	#define IDSMUI_CMDCAP_HANDSIGN     		390
	#define IDSMUI_CMDCAP_ADDSIGN      		391
	#define IDSMUI_CMDCAP_ADDSIGN_PERPAGE 	392
	#define IDSMUI_CMDCAP_ADDKEYBDCMT  		393
	#define IDSMUI_CMDCAP_ADDEKEYSIGN  		394
#else
	#define IDSMUI_CMDCAP_HANDSIGN     		46
	#define IDSMUI_CMDCAP_ADDSIGN      		47
	#define IDSMUI_CMDCAP_ADDSIGN_PERPAGE 	48
	#define IDSMUI_CMDCAP_ADDKEYBDCMT  		49
	#define IDSMUI_CMDCAP_ADDEKEYSIGN  		50
#endif


#define IDSMUI_CMDCAP_SETUP        		51
#define IDSMUI_CMDCAP_LOGONSVR     		52
#define IDSMUI_CMDCAP_LOGOFFSVR    		53
#define IDSMUI_CMDCAP_CHECKSIGNS   		54
#define IDSMUI_CMDCAP_FINGERSIGN   		55
#define IDSMUI_CMDCAP_EXPORTNTKF   		56
#define IDSMUI_CMDCAP_HELP         		57
#define IDSMUI_CMDBAR_NAME         		58
#define IDSMUI_CMDBAR_NAMESP       		59
#define IDSMUI_CMDBAR_NAMESVR      		60
#define IDSMUI_ERR_NONTKOVPCI      		61
#define IDSMUI_ERR_CREATENTKOVPCI  		62
#define IDSMUI_ERR_ADVISEVPCIEVENT 		63
#define IDSMUI_UIMES_STARTPRINTER  		64
#define IDSMUI_UIMES_CONVERTINGNTKF 	65
#define IDSMUI_ERR_CONVERTNTKF_FMT 		66
#define IDSMUI_NTKF_FILEFILTER     		67
#define IDSMUI_ERR_PRINTDOCEXCEL   		68
#define IDSMUI_ERR_PRINTDOCOTHER   		69
#define IDSMUI_ERR_NONTKOVPRINTER  		70
#define IDSMUI_NTKFPASSDLG_TITLE   		71
#define IDSMUI_ERRORSIGNDOCPROTECTED	72
#define IDSMUI_ERRORSIGNERRORPOINT		73
#define IDSMUI_ERRNOOFFICE				74
#define IDSMUI_ONLY_WORDOK				75
#define IDSMUI_ONLY_WPSOK				76

#define IDSMUI_HC_ASKADD_PERPAGE_SIGNS				80
#define IDSMUI_ADDING_SIGNS							81
#define IDSMUI_ERRORADD_PERPAGE_SIGNS				82
#define IDSMUI_ERRORADD_PERPAGE_SIGNS_OR_CANCELED	83
#define IDSMUI_ERR_LOCKDOC							84
#define IDSMUI_UPDATING_SINGS						85
#define IDSMUI_OK_PERPAGE_SIGNS						86
#define IDSMUI_ERRORNOSOFTSIGN						87

#define IDSMUI_HTTPERRORCODE						90
#define IDSMUI_WORDWPSDOC_COUNTCHARS				91
#define IDSMUI_EXCEL_COUNTCHEETS					92

#define IDSMUI_CMDCAP_ADDBARCODE   					95
#define IDSMUI_CMDCAP_QIFENG_2PAGE   				96
#define IDSMUI_CMDCAP_QIFENG_NPAGE   				97

#define IDSMUI_ERRORSIGNSERVERNAME						100
#define IDSMUI_SIGNSLISTDLG_PLZSELECTSIGN				101
#define IDSMUI_EKEYPINERRORREINPUT						102
#define IDSMUI_READINGEKEYINFO							103
#define IDSMUI_LOGINGINSERVER							104
#define IDSMUI_PREPARE_USERENV							105
#define IDSMUI_LOGINSERVER_APPTITLE_FORMAT				106
#define IDSMUI_LOGINSERVER_FAIL							107
#define IDSMUI_LOGINSERVER_FAIL_SERVERFAILWITHCODE		108
#define IDSMUI_LOGINSERVER_FAIL_PARSERESPONSEERROR		109
#define IDSMUI_LOGINSERVER_FAIL_INVALIDSERVER_VERSION	110
#define IDSMUI_LOGINGOFFSERVER							111
#define IDSMUI_CHECKING_USERRIGHTS						112
#define IDSMUI_CHECKRIGHT_FAIL_INVALIDSERVER_VERSION	113
#define IDSMUI_CHECKRIGHT_FAIL							114
#define IDSMUI_CHECKRIGHT_FAIL_SERVERFAILWITHCODE		115
#define IDSMUI_CHECKRIGHT_FAIL_PARSERESPONSEERROR		116
#define IDSMUI_CHECKRIGHT_FAIL_SIGNERROR_PARSEERROR		117
#define IDSMUI_CHECKRIGHT_FAIL_SIGNERROR_NOAVAILSIGNS	118
#define IDSMUI_CHECKRIGHT_FAIL_EKEYSIGNERROR_PARSEERROR 119
#define IDSMUI_CHECKING_USERRIGHTS_ANDREADSIGNLIST		120
#define IDSMUI_DOWNLOADSIGN_DATA						121
#define IDSMUI_DOWNLOADSIGN_FAIL						122
#define IDSMUI_GETSIGNOPTIONS_FAIL_EKEYSIGNERROR_PARSEERROR 123
#define IDSMUI_GETSIGNOPTIONS_FAIL_SIGNERROR_PARSEERROR		124
#define IDSMUI_GETSIGNOPTIONS_FAIL_HANDSIGNERROR_PARSEERROR 125
#define IDSMUI_CHECKRIGHT_USER_NORIGHT					126
#define IDSMUI_CHECKRIGHT_USER_NORIGHT_EKEY				127
#define IDSMUI_BEGIN_TESTSERVER 						128
#define IDSMUI_BEGIN_GETSERVERTIME 						129
#define IDSMUI_GETSERVERTIME_FAIL_PARSEERROR			130
#define IDSMUI_GETSERVERTIME_FAIL_INVALIDSERVER_VERSION 131
#define IDSMUI_GETSERVERTIME_FAIL_SERVERFAILWITHCODE	132
#define IDSMUI_GETSERVERTIME_FAIL_CONNECT				133
#define IDSMUI_DOINGLOGSIGN 							134
#define IDSMUI_DOLOGSIGN_FAIL_INVALIDSERVER_VERSION		135
#define IDSMUI_DOLOGSIGN_FAIL_SERVERFAILWITHCODE		136
#define IDSMUI_DOLOGSIGN_FAIL_PARSERESPONSEERROR		137
#define IDSMUI_DOLOGSIGN_FAIL_CONNECT					138
#define IDSMUI_SIGN2EKEYCHECK 							139
#define IDSMUI_SIGN2EKEYCHECK_NORIGHT_EKEY				140
#define IDSMUI_CHECKSIGNS_FAIL_NOSIGNS 					141
#define IDSMUI_CHECKSIGNS_FAIL_NOCHECKSERVERS 			142
#define IDSMUI_CHECKSIGNS_DOING_GETSIGNSINFO			143
#define IDSMUI_CHECKSIGNS_GETSIGNSINFO_FROMSERVER		144
#define IDSMUI_CHECKSIGNS_FAIL_INVALIDSERVER_VERSION	145
#define IDSMUI_CHECKSIGNS_FAIL_SERVERFAILWITHCODE		146
#define IDSMUI_CHECKSIGNS_FAIL_PARSERESPONSEERROR		147
#define IDSMUI_CHECKSIGNS_FAIL_CONNECT 					148
#define IDSMUI_GETTING_DOCSIGNS 						149
#define IDSMUI_GETTING_CHANGED_SERVERS 					150
#define IDSMUI_CHECKSIGNS_FAIL_NOSIGNS_FROMSERVER		151
#define IDSMUI_TESTSERVER_INFO 							152
#define IDSMUI_GETTINGSERVER_INFO 						153
#define IDSMUI_SERVER_NO_AVAIL_SIGN						154

#define IDSMUI_SIGNSOURCE_FROMURL 			157
#define IDSMUI_SIGNINFO_SIGNSN_W			158
#define IDSMUI_SIGNINFO_EKEYSN_W			159
#define IDSMUI_SIGNINFO_SIGNGUID_W			160
#define IDSMUI_SIGNINFO_SIGNSERVERNAME_W	161
#define	IDSMUI_SIGNINFO_USERNAME_W			162
#define IDSMUI_SIGNINFO_SIGNNAME_W			163
#define IDSMUI_SIGNINFO_SIGNUSER_W			164
#define IDSMUI_SIGNINFO_TIMESTAMP_W			165
#define IDSMUI_SIGNINFO_APPNAME_W			166
#define IDSMUI_SIGNINFO_CLIENTIP_W			167
#define IDSMUI_CHECKSIGNS_NOSIGN_ON_SERVER 	168
#define IDSMUI_CHECKSIGNS_SERVER_FAIL 		169
#define IDSMUI_CHECKSIGNS_SERVER_OK 		170
#define IDSMUI_HC_LOG_SIGNOP0				171
#define IDSMUI_HC_LOG_SIGNOP1				172
#define IDSMUI_HC_LOG_SIGNOP2				173
#define IDSMUI_HC_LOG_SIGNOP3				174
#define IDSMUI_HC_LOG_SIGNOP4				175
#define IDSMUI_HC_LOG_SIGNOP5				176
#define IDSMUI_HC_LOG_SIGNOP6				177
#define IDSMUI_HC_LOG_SIGNOP7				178
#define IDSMUI_HC_LOG_SIGNOP8				179
#define IDSMUI_HC_LOG_SIGNTYPE0				180
#define IDSMUI_HC_LOG_SIGNTYPE1				181
#define IDSMUI_HC_LOG_SIGNTYPE2				182
#define IDSMUI_HC_LOG_SIGNTYPE3				183
#define IDSMUI_HC_LOG_SIGNTYPE4				184
#define IDSMUI_HC_LOG_SIGNTYPEOTHER			185
#define IDSMUI_EKEYMES_ERR_USAGE 			186


//系统设置对话框
#define IDCMUI_STATIC_CFGNMTXT				300
#define IDCMUI_STATIC_CFGSIGNTXT			301
#define IDCMUI_CHECKADDSIGNTOP				302
#define IDCMUI_CHECKACCEPTREV				303
#define IDCMUI_RADIOCURSOR					304
#define IDCMUI_RADIOSEEONE					305
#define IDCMUI_RADIOSEEMORE					306
#define IDCMUI_RADIOCENTER					307
#define IDCMUI_RADIOLEFT					308
#define IDCMUI_STATICISSUERNAME				309
#define IDCMUI_STATICLANGCODE				310
#define IDCMUI_CHECKLOCKSIGN				311
#define IDCMUI_CHECKLOCKDOC					312

#define IDCMUI_STATICFILEINFO				320

//登录对话框
#define IDSMUI_LOGINDLG_TITLE				330
#define IDCMUI_STATICUSERNAME				331
#define IDCMUI_STATICPASSWORD				332
#define IDCMUI_CHECKREMEMBERUSER			333
#define IDCMUI_CHECKUSEEKEY					334
#define IDCMUI_STATICINFO_INSERTEKEY		335
#define IDCMUI_BUTTON_LOGIN					336
#define IDSMUI_SELEKEYDLGTITLE				337

//签章服务设定对话框
#define IDCMUI_STATIC_SVRCFG				340
#define IDCMUI_STATICSERVERNAME				341
#define IDCMUI_STATICINFO_SVRCFG			342
#define IDCMUI_BUTTON_TESTSERVER			343
#define IDCMUI_CHECKUSEDEFPASS				344

//选择印章列表对话框
#define IDSMUI_SELECTSIGN_DLG_TITLE			350
#define IDCMUI_SELECTSIGN_DLG_TABT			351
#define IDCMUI_BUTTON_CONTINUE				352
#define IDCMUI_SELECTSIGN_DLG_INPUTINFO		353

//检验印章对话框
#define IDSMUI_CHECKSIGN_DLG_TITLE			360
#define IDCMUI_STATICDOCSIGNS_LIST			361
#define IDCMUI_STATIC_SVRCHKINFO			362
#define IDCMUI_BUTTON_FINDPOS				363

//选择多页印章位置对话框
#define IDSMUI_PAGEPOSDLG_TITLE				370
#define IDSMUI_PAGEPOSDLG_TABT				371
#define IDCMUI_RADIO_PAGETOP				372
#define IDCMUI_RADIO_PAGMIDDLE				373
#define IDCMUI_RADIO_PAGBOTTOM				374

//骑缝章相关信息
#define IDSMUI_ERROR_QIFENGNEED2MOREPAGES			380
#define IDSMUI_ERROR_ADD_QIFENG_SIGNS_ORCANCEL		381
#define IDSMUI_ERROR_ADD_QIFENG_SIGNS				382

//错误信息
#define IDSMUI_LOGINSERVER_FAIL_INVALIDCERT		410
#define IDSMUI_LOGINSERVER_FAIL_USERNAMEINVALID	411

// #if defined(NTKO_CUSTOM_JIANGSU_CA)
// 	#define IDSMUI_GETSIGNOPTIONS_FAIL_PARSEERROR	501
// 	#define IDSMUI_GETUSERIGHT_FAIL_PARSEERROR		601
// #endif

#endif